---
- name: Install bash
  become: true
  ansible.builtin.package:
    pkg:
      - bash
      - fzf
      - bash-completion
    state: latest
  tags: [bash]

- name: Check if .bashrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bashrc"
  register: bash_bashrc
  tags: [bash]

- name: Ensure .bashrc contains local bin directory
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'export PATH="$PATH:$HOME/.local/bin"'
  when: bash_bashrc.stat.exists
  tags: [bash, system]
