---
- name: Dot files
  hosts: localhost
  gather_facts: true
  connection: local
  roles:
    - system
    - git
    - tmux
    - bash
    - starship
    - nvim
    - node
    - python
    - lua
    - direnv
    - docker
    - projects
