---
- name: Install Direnv
  become: true
  ansible.builtin.apt:
    pkg:
      - direnv
    state: latest
  tags:
    - direnv

- name: Check if .bashrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bashrc"
  register: bashrc
  tags:
    - direnv

- name: Update .bashrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'eval "$(direnv hook bash)"'
  when: bashrc.stat.exists
  tags:
    - direnv
