---
- name: Install uv (package manager for Python)
  ansible.builtin.shell: >
    curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/uv"
  tags:
    - python

- name: Check if .zshrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrc
  tags:
    - python

- name: Update .zshrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'eval "$(uv generate-shell-completion zsh)"'
  when: zshrc.stat.exists
  tags:
    - python
