---
- name: Download uv install script
  ansible.builtin.get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/uv-install.sh
    mode: "0755"
  tags: [python]

- name: Run uv install script
  ansible.builtin.command: /tmp/uv-install.sh
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/uv"
  tags: [pyhton]

- name: Check if .bashrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bashrc"
  register: python_bashrc
  tags: [python]

- name: Update .bashrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'eval "$(uv generate-shell-completion bash)"'
  when: python_bashrc.stat.exists
  tags: [python]

- name: Check if .zshrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: python_zshrc
  tags: [python]

- name: Update .zshrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} ANSIBLE: uv"
    block: |
      autoload -Uz compinit
      compinit
      command -v uv >/dev/null && eval "$(uv generate-shell-completion zsh)"
  when: python_zshrc.stat.exists
  tags: [python]
