---
- name: Install uv (package manager for Python)
  ansible.builtin.shell: >
    curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/uv"
  tags:
    - python

- name: Check if .bashrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bashrc"
  register: bashrc
  tags:
    - python

- name: Update .bashrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'eval "$(uv generate-shell-completion bash)"'
  when: bashrc.stat.exists
  tags:
    - python
