---
- name: Update system
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true
  tags:
    - system

- name: Install misc packages
  become: true
  ansible.builtin.apt:
    pkg:
      - git
      - curl
      - wget
      - jq
      - shellcheck
      - fzf
    state: latest
  tags:
    - system

- name: Create local bin directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "0755"
  tags:
      - system

- name: Ensure .zshrc contains local bin directory
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'export PATH="$PATH:$HOME/.local/bin"'
  tags:
      - system

