---
- name: Update system
  become: true
  ansible.builtin.package:
    update_cache: true
  when: ansible_facts.pkg_mgr == 'apt'
  tags: [system]

- name: Update pacman cache
  become: true
  community.general.pacman:
    update_cache: true
  when: ansible_facts.pkg_mgr == 'pacman'
  tags: [system]

- name: Install misc packages
  become: true
  ansible.builtin.package:
    pkg:
      - git
      - curl
      - wget
      - jq
      - shellcheck
      - fzf
      - universal-ctags
    state: latest
  tags: [system]

- name: Create local bin directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "0755"
  tags: [system]

- name: Copy sessionizer to bin directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/s"
    mode: "0755"
  loop:
    - scripts/sessionizer.sh
  tags: [system, scripts]
