---
- name: Install Zsh
  become: true
  ansible.builtin.package:
    pkg:
      - git
      - zsh
      - fzf
    state: latest
  tags: [zsh]

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-autosuggestions"
  tags: [zsh]

- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-syntax-highlighting"
  tags: [zsh]

- name: Install zsh-nvm plugin
  ansible.builtin.git:
    repo: https://github.com/lukechilds/zsh-nvm
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-nvm"
  tags: [zsh]

- name: Check if .zshrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zsh_zshrc
  tags: [zsh]

- name: Ensure .zshrc contains local bin directory
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'export PATH="$PATH:$HOME/.local/bin"'
    - "source {{ ansible_env.HOME }}/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
    - "source {{ ansible_env.HOME }}/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
    - "source {{ ansible_env.HOME }}/.zsh/zsh-nvm/zsh-nvm.plugin.zsh"
  when: zsh_zshrc.stat.exists
  tags: [zsh, system]
