---
- name: Install Zsh
  become: true
  ansible.builtin.apt:
    pkg:
      - git
      - zsh
      - curl
    state: latest
  tags:
    - zsh

- name: Install oh-my-zsh
  ansible.builtin.shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  tags:
    - zsh

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  tags:
    - zsh

- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  tags:
    - zsh

- name: Install zsh-nvm plugin
  ansible.builtin.git:
    repo: https://github.com/lukechilds/zsh-nvm
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-nvm"
  tags:
    - zsh

- name: Copy .zshrc
  ansible.builtin.template:
    src: templates/zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: "0644"
  tags:
    - zsh

- name: Set default shell to zsh
  become: true
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  tags:
    - zsh

- name: Ensure .zshrc contains local bin directory
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'export PATH="$PATH:$HOME/.local/bin"'
  tags:
      - system
