---
- name: Install Zsh
  become: true
  ansible.builtin.apt:
    pkg:
      - git
      - zsh
      - curl
    state: latest
  when: shell == "zsh"
  tags:
    - zsh

- name: Install oh-my-zsh
  ansible.builtin.shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: shell== "zsh"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  tags:
    - zsh

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  when: shell == "zsh"
  tags:
    - zsh

- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  when: shell == "zsh"
  tags:
    - zsh

- name: Install zsh-nvm plugin
  ansible.builtin.git:
    repo: https://github.com/lukechilds/zsh-nvm
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-nvm"
  when: shell == "zsh"
  tags:
    - zsh

- name: Install zsh-pyenv plugin
  ansible.builtin.git:
    repo: https://github.com/mattberther/zsh-pyenv
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-pyenv"
  when: shell == "zsh"
  tags:
    - zsh

- name: Copy .zshrc
  ansible.builtin.template:
    src: templates/zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: "0644"
  when: shell == "zsh"
  tags:
    - zsh

- name: Set default shell to zsh
  become: true
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  when: shell == "zsh"
  tags:
    - zsh
