---
- name: Install Git
  become: true
  ansible.builtin.package:
    pkg:
      - git
    state: latest
  tags:
    - git

- name: Set email in .gitconfig
  git_config:
    name: user.email
    scope: global
    value: "{{ email }}"
  tags:
    - git

- name: Set name in .gitconfig
  git_config:
    name: user.name
    scope: global
    value: "{{ first_name }} {{ last_name }}"
  tags:
    - git

- name: Set default branch name in .gitconfig
  git_config:
    name: init.defaultBranch
    scope: global
    value: "main"
  tags:
    - git

- name: Set default editor to nvim in .gitconfig
  git_config:
    name: core.editor
    scope: global
    value: "{{ default_editor }}"
  tags:
    - git
