---
- name: Install Docker dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: latest
  tags:
    - docker

- name: Create apt keyrings folder
  become: true
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    mode: "0755"
  tags:
    - docker

- name: Download Docker GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  tags:
    - docker

- name: Get System Architecture
  ansible.builtin.command: "dpkg --print-architecture"
  register: dpkg_architecture
  changed_when: false
  failed_when: false
  check_mode: false
  tags:
    - docker

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{
      ansible_distribution_release }} stable
    mode: "0644"
  become: true
  tags:
    - docker

- name: Install Docker Engine
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
  tags:
    - docker

- name: Enable Docker service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: docker
    state: started
  tags:
    - docker

- name: Add user to Docker group
  become: true
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ user }}"
  tags:
    - docker

- name: Restart Docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
  tags:
    - docker
