---
- name: Download Starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-install.sh
    mode: "0755"
  tags: [starship]

- name: Run Starship install script
  become: true
  ansible.builtin.command: /tmp/starship-install.sh -y
  args:
    creates: /usr/local/bin/starship
  tags: [starship]

- name: Check if .bashrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bashrc"
  register: starship_bashrc
  tags: [starship]

- name: Update .bashrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'eval "$(starship init bash)"'
  when: starship_bashrc.stat.exists
  tags: [starship]

- name: Check if .zshrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: starship_zshrc
  tags: [starship]

- name: Update .zshrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    state: present
  loop:
    - 'eval "$(starship init zsh)"'
  when: starship_zshrc.stat.exists
  tags: [starship]
